language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
sudo: false
before_script:
- travis_retry composer self-update
- npm install -g grunt-cli
- npm install
- if [ $(phpenv version-name) != "5.3" ]; then composer install; fi
- if [ $(phpenv version-name) != "5.3" ]; then mysql -e 'create database xe_test;'; fi
- if [ $(phpenv version-name) != "5.3" ]; then echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis')
  WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root; fi
- if [ $(phpenv version-name) != "5.3" ]; then php -S localhost:8000 & fi
script:
- grunt lint
- grunt minify
- if [ $(phpenv version-name) != "5.3" ]; then ./vendor/bin/codecept build; fi
- if [ $(phpenv version-name) != "5.3" ]; then ./vendor/bin/codecept run -d --fail-fast --env travis; fi
notifications:
  email: false
